[package]
name = "kelp-cli"
description = "Save, share, and restore your project"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "kelp"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
fs2.workspace = true
ignore.workspace = true
kelp-core.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
similar.workspace = true
diffy.workspace = true
tempfile.workspace = true
uuid.workspace = true

[dev-dependencies]
axum.workspace = true
kelp-remote = { path = "../remote" }
tokio.workspace = true

[lints]
workspace = true
